# campus EXTREME VIO profile - source this, then run the dry-run below.
# Same stadium circuit as BASELINE/STRESS, generated by
# tools/campus_vio_corridor.py build (EXT_* constants). The waypoint file
# encodes the speeds outright (STRESS=1, knots uniform in spline phase):
# 20 kph sprint held on the long straight past the elbow (measured peak
# 5.74 m/s, >=5.5 m/s held 1.13 s), two hard stop-and-go events to a
# 0.25 m/s crawl (measured peak |a| 8.79 m/s^2, inside the band the IMU
# spline chain reproduces to <2%), 2.0 m/s cap turns (gyro peak
# 2.68 rad/s), a one-sided
# lane weave on the return leg reaching 0.9 m past the centreline (6
# self-crossings of the outbound lane, tube max 1.33 m < 2 m), and a
# full-lap vertical sweep over 0.30..1.70 m above ground.
#
# VERTICAL BAND: 0.30..1.70 m above ground, VERIFIED by eye in the
# playground (2026-09-18): renders stay coherent to 1.7 m; breakdown
# starts ~3.6 m off the 0.64 m capture plane. EXT_BAND_M in the builder
# is the knob if a different band is ever wanted.
#
# Knob read sites: identical to campus_stress_env.sh (VioConfig
# vio_trajectory.py:207-231, STRESS applied :315/:839). VIO_FPS=45 keeps
# the per-frame displacement under TRACKABLE_PX=50 (measured peak
# 26.4 px). VIO_MOTION_S MUST stay 31.8 = 29.8 s lap + RAMP_S/2;
# changing it rescales every speed.
# Set VILOTA_DATASETS to the folder that holds main_campus/ before sourcing.
export SCENE_ALIGNMENT="${VILOTA_DATASETS:?set VILOTA_DATASETS to the folder that holds main_campus/}/main_campus/lidar_alignment.json"
export PLAYGROUND_CALIB=calibration_files/DP180IP-30020104.json
export VIO_TRAJ=1
export STRESS=1
export STATIONARY_LEAD_S=3
export VIO_MOTION_S=31.8
export VIO_FPS=45
export VIO_TRAJ_NPZ=mcap_outputs/campus_extreme_truth.npz
export VIO_WAYPOINTS=campus_vio/campus_extreme_waypoints.csv

# Headless dry-run (CPU only; 6 board-visibility FAILs expected, no
# boards on the corridor - kinematics/px/C2 all PASS):
#   python -m threedgrut_playground.utils.vio_trajectory --dry-run \
#     --waypoints campus_vio/campus_extreme_waypoints.csv \
#     --cloud campus_vio/campus_overhead_board_units.csv \
#     --alignment $SCENE_ALIGNMENT \
#     --npz $VIO_TRAJ_NPZ --rerun mcap_outputs/campus_extreme.rrd
# Tube / kinematics audit:
#   python tools/campus_vio_corridor.py check --npz $VIO_TRAJ_NPZ
